openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for user authentication and registration
servers:
  - url: http://localhost:8000/api/v1
    description: Development server
paths:
  /auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account with the provided credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  minLength: 8
                  example: "secure_password_123"
              required:
                - email
                - password
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        description: JWT token for authentication
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "REGISTRATION_SUCCESS"
                      message:
                        type: string
                        example: "User registered successfully"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: null
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "VALIDATION_ERROR"
                      message:
                        type: string
                        example: "Invalid email format or password too short"
        '409':
          description: Conflict - user already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: null
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "USER_EXISTS"
                      message:
                        type: string
                        example: "User with this email already exists"